// Portable presentation only. No credentials, requests, job state, or pipeline logic.
import { BAC_QUAI_CUTOUT } from './bac-quai-cutout-art.js';

export const REEL_WORLD_HEADER = '<div class="world-brand"><span class="world-monogram" aria-hidden="true">qn</span><span>QN REEL WORLD<small>A little footage. A world of stories.</small></span></div><nav class="operator-nav" aria-label="Main navigation"><button data-view="production" aria-current="page">Production</button><button data-view="diagnostics">Diagnostics</button></nav><button class="operator-link" data-view="settings">Settings</button>';

const workshop = '<img class="world-art" src="' + BAC_QUAI_CUTOUT + '" width="720" height="720" alt="Bác Quài welcomes you with a thumbs-up." />';

export const REEL_WORLD_PRODUCTION = `
  <div id="operator-setup">
    <aside class="world-welcome">
      <div class="world-welcome-copy"><p class="world-eyebrow">Welcome to the workshop</p><h1>Small clips.<br><em>Big stories.</em></h1><p>Everyday moments, brought together.</p></div>
      <figure class="world-portrait">${workshop}<figcaption><span>YOUR HOST</span><strong>Bác Quài</strong><span>A familiar face. A world of possibilities.</span></figcaption></figure>
    </aside>
    <div class="world-table">
      <div class="world-table-heading"><span class="world-chapter">01 / A new reel</span><h2>Bring your footage.</h2><p>Choose 2–10 clips. Start with the moments you love.</p></div>
      <div id="operator-connections"></div>
      <div id="operator-sources"></div>
      <div class="world-create-row"><p id="world-selection-hint">Select at least 2 clips to begin.</p><div id="operator-start"></div></div>
      <p class="world-table-note">Your moments are the starting point.</p>
    </div>
  </div>
  <div id="operator-processing" class="operator-state" hidden aria-live="polite">
    <div class="world-processing-art">${workshop}<span class="world-art-caption">Behind the scenes at QN Reel World</span></div>
    <div class="world-processing-copy"><p class="world-eyebrow">Inside the workshop</p><h1 id="operator-activity">Preparing footage</h1><p id="operator-explanation"></p><div class="operator-progress-stage"><output id="operator-progress-number" aria-hidden="true" hidden></output><progress id="operator-progress" aria-label="Reported job progress"></progress><span class="world-activity-light" aria-hidden="true"></span></div><div class="operator-state-actions"><button class="operator-link" data-open="diagnostics">View diagnostics <span aria-hidden="true">↗</span></button><button class="btn" id="operator-new-reel" hidden>Start another reel</button></div><p id="operator-job" class="operator-status"></p></div>
  </div>`;

export const REEL_WORLD_STYLES = `
/* QN Reel World: presentation tokens and scenes. Existing DOM IDs are adapters. */
:root{color-scheme:light;--world-paper:#f4f0e6;--world-ink:#243d32;--world-muted:#6f7566;--world-line:#d7d8c9;--world-green:#254d3b;--world-lime:#d7e888;--world-rust:#945539;--studio-lime:#d7e888}
*{box-sizing:border-box}body{margin:0;background:var(--world-paper);color:var(--world-ink);font:15px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}button,input{font:inherit}[hidden]{display:none!important}
.operator-header{height:96px;max-width:1700px;margin:auto;padding:0 4vw;display:grid;grid-template-columns:1fr auto 1fr;align-items:center;border-bottom:1px solid var(--world-line);gap:32px}
.world-brand{display:flex;gap:13px;align-items:center;font-size:15px;font-weight:750;letter-spacing:.05em;white-space:nowrap}.world-monogram{display:grid;place-items:center;width:45px;height:45px;background:var(--world-green);color:var(--world-paper);border-radius:50%;font:italic 30px Georgia,serif;letter-spacing:-.1em;padding-right:5px}.world-brand small{display:block;font-size:10px;font-weight:400;letter-spacing:.015em;margin-top:3px;color:var(--world-muted)}
.operator-nav{display:flex;gap:32px}.operator-nav button,.operator-link{border:0;background:none;color:var(--world-muted);padding:12px 0;cursor:pointer}.operator-nav button{position:relative;font-size:14px}.operator-nav button[aria-current=page]{color:var(--world-ink);font-weight:600}.operator-nav button[aria-current=page]:after{content:"";position:absolute;height:2px;background:var(--world-green);bottom:0;left:0;right:0}.operator-header>.operator-link{justify-self:end;font-size:13px}
button:focus-visible,input:focus-visible{outline:3px solid #9d6a25;outline-offset:4px}.operator-link:hover,.operator-nav button:hover{color:var(--world-ink)}
.operator-view{max-width:1600px;margin:auto;padding:44px 4vw 40px}.operator-view h1{font:400 54px/1.03 Georgia,serif;letter-spacing:-.045em;margin:0 0 22px}.operator-view p{color:var(--world-muted);font-size:14px;line-height:1.65}.operator-view .btn{background:transparent;color:var(--world-ink);border:1px solid #acb7a5;border-radius:7px;padding:11px 17px;transition:background .16s,transform .16s;cursor:pointer;font-size:14px;font-weight:600}.operator-view .btn:hover{background:#e4e8d9}.operator-view .btn:active{transform:translateY(1px)}.operator-view .btn.primary{background:var(--world-green);border-color:var(--world-green);color:#f8f8ee}.operator-view .btn.primary:hover{background:#183d2c}.operator-view .btn:disabled{opacity:1;background:#e6e6da;color:#6d7563;border-color:#d8dccb;cursor:not-allowed}
#operator-setup{display:grid;grid-template-columns:minmax(300px,.95fr) minmax(420px,1.15fr);gap:5vw;align-items:start}
.world-welcome{position:relative;min-width:0}.world-welcome-copy{padding:4px 0 0 8px}.world-eyebrow{font-size:11px!important;letter-spacing:.12em;text-transform:uppercase;font-weight:600;color:var(--world-rust)!important;margin:0 0 18px}.world-welcome h1{font-size:clamp(48px,4.9vw,74px);line-height:.99;margin-bottom:17px}.world-welcome h1 em{font-weight:400;color:#6b7954}.world-welcome-copy>p:last-child{margin-bottom:25px}
.world-portrait{margin:0;position:relative;border-radius:120px 8px 8px 8px;overflow:hidden;background:#e8e4d3}.world-art{width:100%;height:100%;object-fit:contain;display:block}.world-portrait>.world-art{aspect-ratio:1.48;object-position:center bottom;padding:12px 18px 0}.world-portrait figcaption{position:relative;display:grid;grid-template-columns:1fr auto;gap:1px 15px;padding:15px 22px;background:#294536;color:#faf5e8}.world-portrait figcaption span:first-child{font-size:9px;letter-spacing:.16em;opacity:.7}.world-portrait figcaption strong{font:italic 25px Georgia,serif;grid-column:1}.world-portrait figcaption span:last-child{grid-column:2;grid-row:1 / span 2;align-self:center;font-size:10px;max-width:120px;text-align:right;color:#d6ddc9}
.world-table{min-width:0;padding:5px 0 0}.world-table-heading h2{font:400 37px/1.12 Georgia,serif;letter-spacing:-.025em;margin:12px 0 10px}.world-table-heading p{margin:0 0 20px}.world-chapter{font-size:11px;color:var(--world-rust);letter-spacing:.08em;text-transform:uppercase}
#operator-connections{display:flex;align-items:center;flex-wrap:wrap;gap:8px 15px;padding:0 0 17px}.operator-view #drive-status{color:#59634f;font-size:12px;margin:0;display:flex;gap:7px;align-items:center}.operator-view #drive-status:before{content:"";display:inline-block;width:6px;height:6px;border-radius:50%;background:#a5ab9a}#operator-connections:has(#drive-connect[hidden]) #drive-status:before{background:#46724f}#operator-connections .btn{font-size:12px;padding:7px 12px;background:#fffdf5;border-color:#c9cebd}#operator-connections .status{width:100%;font-size:12px;min-height:0;color:var(--world-muted);margin:0}#operator-connections .status.error{color:#a24430}
.operator-view .source-panel{display:flex;flex-direction:column;margin:0;padding:0;background:none;border:0;border-radius:0}.source-panel>.panel-head{order:0;align-items:center;margin:0;padding:13px 17px;background:#e8e9db;border-radius:9px 9px 0 0}.operator-view .panel-title{font-size:12px;font-weight:600;letter-spacing:.025em}.operator-view #clip-count{font:12px ui-monospace,monospace;color:#68745c}
.operator-view #selected-files{order:1;display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;padding:18px;min-height:196px;max-height:330px;overflow:auto;background:#e8e9db;counter-reset:footage}.operator-view #selected-files:has(>.muted){display:flex;align-items:center;justify-content:center;padding:22px;min-height:192px}.operator-view #selected-files>.muted{color:#67715b;font-size:13px;text-align:center;max-width:240px;line-height:1.6}.operator-view #selected-files>.muted:before{content:"";display:block;width:74px;height:51px;margin:0 auto 18px;border:1px solid #8d9b7c;border-radius:4px;background:linear-gradient(90deg,transparent 7px,#8d9b7c 7px,#8d9b7c 8px,transparent 8px,transparent calc(100% - 8px),#8d9b7c calc(100% - 8px),#8d9b7c calc(100% - 7px),transparent calc(100% - 7px));box-shadow:5px -5px 0 #d5dbc4,6px -6px 0 #aeb99d;transform:rotate(-6deg)}
.operator-view .source-panel .drive-actions{order:2;display:flex;justify-content:center;margin:0;padding:0 18px 17px;background:#e8e9db;border-radius:0 0 9px 9px}.operator-view #select-files{width:auto;min-width:185px;background:#f9faf1;border-color:#b6c1a4;padding:9px 18px;font-size:13px}.operator-view #select-files:not(:disabled):hover{background:#d7e888}.operator-view #select-files:disabled{background:#e3e6d6;color:#727b65;border-color:#c5cdb8}
.operator-view .file{counter-increment:footage;display:grid;grid-template-columns:1fr auto;gap:8px;align-items:start;background:#fffdf4;border:0;border-radius:3px;padding:9px;box-shadow:0 3px 8px #2e3f2010;min-width:0;transition:transform .16s}.operator-view .file:hover{transform:translateY(-2px)}.operator-view .thumb{grid-column:1 / -1;display:flex;justify-content:space-between;align-items:center;width:100%;height:67px;border-radius:2px;background:#d5dec4;color:#526848;padding:10px;font-size:12px}.operator-view .thumb:before{content:counter(footage,decimal-leading-zero);font:italic 32px Georgia,serif}.operator-view .file-body{min-width:0}.operator-view .file-name{font-size:11px;color:#31432b;font-weight:500}.operator-view .file-meta{color:#74806b;font-size:10px;margin-top:4px}.operator-view .remove{color:#5c6c52;padding:0;width:21px;height:25px;font-size:20px}.operator-view .remove:hover{color:#9f442f}
.operator-view .source-panel .auth{order:3;display:grid;grid-template-columns:auto 1fr;gap:6px 12px;align-items:center;margin:0;padding:16px 0 0}.operator-view .auth .label{font-size:11px;font-weight:500;color:#68735e;letter-spacing:0;text-transform:none}.operator-view .auth input{width:100%;background:transparent;border:0;border-bottom:1px solid #afb8a3;border-radius:0;color:var(--world-ink);padding:8px 0;font-size:13px;margin:0}.operator-view .auth .status{grid-column:2;font-size:11px;min-height:0}.operator-status{font-size:11px!important;color:#576d46!important;overflow-wrap:anywhere}.source-panel>.operator-status{order:3;margin:12px 0 0}.source-panel>.operator-status:before{content:"✓";margin-right:7px}
.world-create-row{display:flex;justify-content:space-between;align-items:center;gap:15px;margin-top:20px}.world-create-row>p{margin:0;font-size:11px;max-width:190px}#operator-start .btn{display:flex;gap:26px;align-items:center;white-space:nowrap;padding:13px 20px;font-size:14px}#operator-start .btn:after{content:"↗";font-size:19px}.world-table-note{font:italic 13px Georgia,serif!important;text-align:right;margin:16px 0 0!important;color:#838b76!important}
#operator-processing{display:grid;grid-template-columns:minmax(300px,1.05fr) minmax(330px,1fr);gap:6vw;align-items:center;min-height:560px;animation:world-enter .3s ease-out}.world-processing-art{position:relative;border-radius:12px 120px 12px 12px;overflow:hidden;background:#e8e4d3;align-self:stretch;min-height:440px}.world-processing-art .world-art{position:absolute;object-position:center bottom;padding:24px 24px 44px}.world-art-caption{position:absolute;left:0;right:0;bottom:0;padding:22px;background:#243d32;color:#e8ecd9;font:italic 16px Georgia,serif}.world-processing-copy{padding:30px 0;min-width:0}#operator-activity{font-size:clamp(42px,4.5vw,65px);max-width:560px}#operator-explanation{max-width:370px;font-size:15px}.operator-progress-stage{margin:32px 0;max-width:380px}#operator-progress-number{font:italic 70px/1 Georgia,serif;color:#577447;display:block;margin-bottom:22px}#operator-progress{display:block;width:100%;height:5px;border:0;border-radius:5px;overflow:hidden;accent-color:var(--world-green)}#operator-progress::-webkit-progress-bar{background:#dce1cf}#operator-progress::-webkit-progress-value{background:#577447;transition:width .3s}#operator-progress::-moz-progress-bar{background:#577447}.world-activity-light{display:none;width:9px;height:9px;border-radius:50%;background:#719455;box-shadow:0 0 0 7px #e4e8d7}.operator-progress-stage:has(#operator-progress:not([value]):not([hidden])) .world-activity-light{display:block;animation:world-breathe 2.4s ease-in-out infinite}.operator-progress-stage:has(#operator-progress:not([value])) #operator-progress{display:none}.operator-progress-stage:has(#operator-progress[hidden]){display:none}.operator-state-actions{display:flex;gap:22px;flex-wrap:wrap;align-items:center;margin-top:26px}.operator-state-actions .operator-link{font-size:13px;color:#455e39}#operator-job{margin-top:45px;color:#7f8874!important;font:10px ui-monospace,monospace!important}
/* Review can replace the scene body when a real render adapter exists. No control is mounted today. */
.world-review{display:grid;grid-template-columns:minmax(0,1fr) 280px;gap:36px}.world-review video{display:block;width:100%;max-height:75vh;background:#16281f;object-fit:contain}
body:has(#operator-diagnostics:not([hidden])){background:#14291f;color:#e2e9dc;color-scheme:dark}body:has(#operator-diagnostics:not([hidden])) .operator-header{border-color:#344d3d;color:#e2e9dc}body:has(#operator-diagnostics:not([hidden])) .operator-nav button,body:has(#operator-diagnostics:not([hidden])) .operator-link{color:#b7c8ad}body:has(#operator-diagnostics:not([hidden])) .operator-nav button[aria-current=page]:after{background:#d7e888}body:has(#operator-diagnostics:not([hidden])) .world-brand small{color:#a3b79a}body:has(#operator-diagnostics:not([hidden])) .world-monogram{background:#d7e888;color:#233e2e}
#operator-diagnostics{max-width:1550px;padding-top:34px}#operator-diagnostics h1{font:400 37px Georgia,serif;margin-bottom:10px}#operator-diagnostics h2{font-size:16px}#operator-diagnostics>p{font-size:13px;color:#aabfa0}#operator-diagnostics .app{display:grid;grid-template-columns:minmax(0,1fr) 270px;min-height:0}#operator-diagnostics .main{padding:0 23px 0 0}#operator-diagnostics .workspace{display:block}#operator-diagnostics .steps{grid-template-columns:repeat(auto-fit,minmax(140px,1fr));gap:14px}#operator-diagnostics .step-name{white-space:normal;font-size:12px}#operator-diagnostics .rightbar{padding:0 0 0 20px;background:none}#operator-diagnostics pre{font-size:12px}.operator-log{white-space:pre-wrap;overflow-wrap:anywhere;background:#102219;padding:18px;font:12px/1.6 ui-monospace,monospace;margin-bottom:24px}#operator-settings{max-width:750px;padding-top:60px}#operator-settings h2{font-size:18px;margin-top:30px}#operator-settings .auth{padding:20px 0;max-width:480px}
@keyframes world-breathe{0%,100%{opacity:.35}50%{opacity:1}}@keyframes world-enter{from{opacity:0;transform:translateY(7px)}to{opacity:1;transform:none}}
@media(min-width:801px) and (max-height:780px){.operator-header{height:80px}.operator-view{padding-top:25px}.world-welcome h1{font-size:59px}.world-welcome-copy>p:last-child{margin-bottom:18px}.world-portrait>.world-art{aspect-ratio:1.7}.world-table-heading h2{font-size:33px}.world-table-heading p{margin-bottom:14px}.operator-view #selected-files{min-height:165px;max-height:250px}.operator-view #selected-files:has(>.muted){min-height:160px}.world-processing-art{min-height:460px}#operator-processing{min-height:500px}}
@media(max-width:1050px){.operator-header{padding:0 3vw;gap:18px}.operator-nav{gap:22px}.world-brand{font-size:12px}.world-brand small{font-size:9px}.operator-view{padding-left:3vw;padding-right:3vw}#operator-setup{gap:4vw;grid-template-columns:minmax(270px,.85fr) minmax(360px,1.1fr)}.world-welcome h1{font-size:55px}.operator-view #selected-files{grid-template-columns:repeat(2,minmax(0,1fr))}.world-portrait figcaption span:last-child{display:none}}
@media(max-width:800px){.operator-header{height:auto;min-height:105px;grid-template-columns:1fr auto;gap:5px 12px;padding:16px 22px 10px}.world-brand{font-size:13px}.world-brand small{font-size:9px}.operator-nav{grid-row:2;grid-column:1 / -1;gap:28px}.operator-nav button{font-size:12px;padding:8px 0}.operator-header>.operator-link{grid-row:1;grid-column:2}.operator-view{padding:24px 22px 40px}#operator-setup{display:flex;flex-direction:column;gap:26px}.world-welcome{width:100%;display:grid;grid-template-columns:1fr 135px;gap:15px;align-items:center}.world-welcome-copy{padding:0}.world-welcome h1{font-size:44px;margin-bottom:12px}.world-welcome-copy>p:last-child{font-size:12px;margin:0}.world-eyebrow{font-size:9px!important;margin-bottom:12px}.world-portrait{border-radius:65px 65px 7px 7px}.world-portrait>.world-art{height:134px;aspect-ratio:auto;object-position:25% center}.world-portrait figcaption{padding:8px 10px}.world-portrait figcaption span:first-child{display:none}.world-portrait figcaption strong{font-size:19px}.world-table{width:100%}.world-table-heading h2{font-size:32px;margin-top:9px}.world-table-heading p{font-size:12px;margin-bottom:16px}.world-chapter{font-size:10px}.operator-view #selected-files{grid-template-columns:repeat(3,minmax(0,1fr));min-height:160px;max-height:330px;padding:13px;gap:9px}.operator-view #selected-files:has(>.muted){min-height:160px}.world-table-note{text-align:center}.world-create-row>p{max-width:160px}#operator-processing{display:flex;flex-direction:column;gap:25px;min-height:0;align-items:stretch}.world-processing-art{height:220px;min-height:0;border-radius:10px 65px 10px 10px}.world-processing-art .world-art{object-position:center 43%}.world-art-caption{padding:12px 15px;font-size:13px}.world-processing-copy{padding:0}#operator-activity{font-size:43px}#operator-explanation{font-size:14px}.operator-progress-stage{margin:24px 0}#operator-progress-number{font-size:57px}#operator-job{margin-top:28px}#operator-diagnostics .app{display:block}#operator-diagnostics .main{padding:0}#operator-diagnostics .rightbar{display:block;padding:20px 0;border:0}.world-review{display:block}}
@media(max-width:390px){.operator-header,.operator-view{padding-left:16px;padding-right:16px}.world-welcome{grid-template-columns:1fr 105px;gap:10px}.world-welcome h1{font-size:38px}.world-portrait>.world-art{height:126px}.world-portrait figcaption strong{font-size:16px}.operator-view #selected-files{grid-template-columns:repeat(2,minmax(0,1fr))}.world-create-row{gap:10px}#operator-start .btn{gap:12px;padding:12px 16px}.world-create-row>p{font-size:10px;max-width:135px}.world-brand{gap:8px;font-size:11px}.world-monogram{width:36px;height:36px;font-size:25px}.world-brand small{font-size:8px}}
@media(prefers-reduced-motion:reduce){*,*:before,*:after{animation:none!important;transition:none!important;scroll-behavior:auto!important}}
`;
